# mkdocs.yml -- MkDocs configuration, all *.md files relative to docs/
site_name: Fortinet AKS reference architecture
repo_url: 'https://github.com/fortinet-solutions-cse/secured-AKS-refarch'
edit_uri: edit/master/docs
site_description: 'Demo code of a reference architecture to secure AKS platform and applications with Fortinet products.'
extra:
  favicon: 'https://fortinet.com/favicon.ico'
  social:
    - type: 'github'
      link: 'https://github.com/fortinet-solutions-cse/secured-AKS-refarch'
theme: readthedocs
extra_css:
 - css/custom.css
nav:
- Home: 'index.md'
- Architecture: 'AKS-Private-secured.md'
- Hands on: 'Hands_on_demos.md'
- Links:
  - Kubernetes load-balancer controller for Fortigate: 'https://github.com/fortinet/k8s-fortigate-ctrl'
  - Official azure templates: 'https://github.com/fortinet/azure-templates'


