--- 
global: 
  imageName: sandbox-cnf
  imageTag: 1.0.0-2
  loadBalancerIP: "10.223.160.60"
  registry: 
    pullSecret: sandbox-cnf
    url: "registry.eccd-cnf.partnervnflab.xgic.ericsson.se:443"
  replicaCount: 3
imageCredentials: 
  registry: 
    url: "registry.eccd-cnf.partnervnflab.xgic.ericsson.se:443"
  repoPath: ""