apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-cnf 
spec:
  replicas: {{.Values.replicaCount}} 
  selector:
    matchLabels:
      app: sandbox-cnf
  template:
    metadata:
      labels:
        app: sandbox-cnf
        app.kubernetes.io/instance: {{ .Release.Name }} 
    spec:
      containers:
      - name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        image: '{{.Values.global.registry.url}}/{{ .Values.global.imageName }}:{{ .Values.global.imageTag }}'
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        imagePullSecrets:
          - name: {{ .Values.global.registry.pullSecret }}
